# Generated by Django 5.1.4 on 2024-12-21 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('period', models.CharField(choices=[('week', 'Неделя'), ('month', 'Месяц'), ('year', 'Год')], max_length=10, verbose_name='Период')),
                ('new_orders_count', models.PositiveIntegerField(default=0, verbose_name='Кол-во новых заказов')),
                ('new_clients_count', models.PositiveIntegerField(default=0, verbose_name='Кол-во новых клиентов')),
                ('total_orders_sum', models.DecimalField(decimal_places=2, default=0.0, max_digits=12, verbose_name='Сумма новых заказов')),
                ('avg_order_sum', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Средняя сумма заказов')),
                ('completed_orders_count', models.PositiveIntegerField(default=0, verbose_name='Кол-во выполненных заказов')),
            ],
            options={
                'verbose_name': 'Отчет',
                'verbose_name_plural': 'Отчеты',
            },
        ),
    ]
